# Generated by Django 2.0 on 2018-06-23 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_number', models.IntegerField(db_index=True)),
                ('destination_number', models.IntegerField()),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricePolice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'STANDARD'), ('R', 'REDUCED')], max_length=1)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PricePolice')),
            ],
        ),
    ]
