# Generated by Django 2.0 on 2018-06-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecord',
            name='id',
        ),
        migrations.AddField(
            model_name='callrecord',
            name='call_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callrecord',
            name='minute_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
