# Generated by Django 2.0 on 2018-06-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180624_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricepolice',
            name='end',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='pricepolice',
            name='start',
            field=models.DateField(default=None),
        ),
    ]
