# Generated by Django 2.0 on 2018-07-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial_Price_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecord',
            name='minute_price',
        ),
        migrations.AddField(
            model_name='callrecord',
            name='call_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='destination_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='source_number',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
