# Generated by Django 2.0 on 2018-07-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180701_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='call_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
